site_name: 希尔伯特的眼泪的个人网站
site_url: https://hilbertear.github.io/Hilbertmath/
site_author: 希尔伯特的眼泪
site_description: 希尔伯特的眼泪的个人网站

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default #日间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - scheme: slate #夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Light Mode

  features:
    - navigation.tabs # 使用tabs分类
    - navigation.tabs.sticky
    - navigation.expand # 展开导航
    - navigation.top # 回到顶部
    - navigation.suggest # 搜索补全
    - navigation.highlight # 高亮关键词
    - navigation.indexes # 索引
  language: zh

nav:
  - 主页: index.md
  - 笔记与讲稿:
      - PDE: pde.md
      - 几何: geometry.md
      - 一些数学感悟: thoughts.md
  - 学习资源:
      - 数学: mathresources.md
      - 物理: phyresources.md
  - 写作:
      - 简介: write.md
      - 收录: write2.md
      - 随笔: write3.md

markdown_extensions:
  - meta
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
